package ipfix

import (
	"bytes"
	"embed"
)

var (
	ianaIpfixIEs map[uint16]InformationElement

	// staticIpfixTypes map[uint16]InformationElement

	certIpfixIEs map[uint16]InformationElement

	//go:embed hack/cert_ipfix.xml hack/cert_ipfix.xml hack/ipfix-information-elements.csv
	spec embed.FS
)

func init() {
	cf, _ := spec.ReadFile("cert_ipfix.xml")
	cb := bytes.NewBuffer(cf)

	iif, _ := spec.ReadFile("ipfix-information-elements.csv")
	ib := bytes.NewBuffer(iif)

	ianaIpfixIEs = MustReadCSV(ib)
	certIpfixIEs = MustReadXML(cb)

	/* staticIpfixTypes = map[uint16]InformationElement{
		0:   {Name: "Reserved", Status: status.Undefined},
		1:   {Name: "octetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		2:   {Name: "packetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		3:   {Name: "deltaFlowCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		4:   {Name: "protocolIdentifier", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		5:   {Name: "ipClassOfService", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		6:   {Name: "tcpControlBits", Constructor: NewUnsigned16, Semantics: semantics.Flags},
		7:   {Name: "sourceTransportPort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		8:   {Name: "sourceIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		9:   {Name: "sourceIPv4PrefixLength", Constructor: NewUnsigned8},
		10:  {Name: "ingressInterface", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		11:  {Name: "destinationTransportPort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		12:  {Name: "destinationIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		13:  {Name: "destinationIPv4PrefixLength", Constructor: NewUnsigned8},
		14:  {Name: "egressInterface", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		15:  {Name: "ipNextHopIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		16:  {Name: "bgpSourceAsNumber", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		17:  {Name: "bgpDestinationAsNumber", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		18:  {Name: "bgpNextHopIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		19:  {Name: "postMCastPacketDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		20:  {Name: "postMCastOctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		21:  {Name: "flowEndSysUpTime", Constructor: NewUnsigned32},
		22:  {Name: "flowStartSysUpTime", Constructor: NewUnsigned32},
		23:  {Name: "postOctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		24:  {Name: "postPacketDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		25:  {Name: "minimumIpTotalLength", Constructor: NewUnsigned64},
		26:  {Name: "maximumIpTotalLength", Constructor: NewUnsigned64},
		27:  {Name: "sourceIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		28:  {Name: "destinationIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		29:  {Name: "sourceIPv6PrefixLength", Constructor: NewUnsigned8},
		30:  {Name: "destinationIPv6PrefixLength", Constructor: NewUnsigned8},
		31:  {Name: "flowLabelIPv6", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		32:  {Name: "icmpTypeCodeIPv4", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		33:  {Name: "igmpType", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		34:  {Name: "samplingInterval", Constructor: NewUnsigned32, Semantics: semantics.Quantity, Status: status.Deprecated},
		35:  {Name: "samplingAlgorithm", Constructor: NewUnsigned8, Semantics: semantics.Identifier, Status: status.Deprecated},
		36:  {Name: "flowActiveTimeout", Constructor: NewUnsigned16},
		37:  {Name: "flowIdleTimeout", Constructor: NewUnsigned16},
		38:  {Name: "engineType", Constructor: NewUnsigned8, Semantics: semantics.Identifier, Status: status.Deprecated},
		39:  {Name: "engineId", Constructor: NewUnsigned8, Semantics: semantics.Identifier, Status: status.Deprecated},
		40:  {Name: "exportedOctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		41:  {Name: "exportedMessageTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		42:  {Name: "exportedFlowRecordTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		43:  {Name: "ipv4RouterSc", Constructor: NewIPv4Address, Semantics: semantics.Default, Status: status.Deprecated},
		44:  {Name: "sourceIPv4Prefix", Constructor: NewIPv4Address, Semantics: semantics.Default},
		45:  {Name: "destinationIPv4Prefix", Constructor: NewIPv4Address, Semantics: semantics.Default},
		46:  {Name: "mplsTopLabelType", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		47:  {Name: "mplsTopLabelIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		48:  {Name: "samplerId", Constructor: NewUnsigned8, Semantics: semantics.Identifier, Status: status.Deprecated},
		49:  {Name: "samplerMode", Constructor: NewUnsigned8, Semantics: semantics.Identifier, Status: status.Deprecated},
		50:  {Name: "samplerRandomInterval", Constructor: NewUnsigned32, Semantics: semantics.Quantity, Status: status.Deprecated},
		51:  {Name: "classId", Constructor: NewUnsigned8, Semantics: semantics.Identifier, Status: status.Deprecated},
		52:  {Name: "minimumTTL", Constructor: NewUnsigned8},
		53:  {Name: "maximumTTL", Constructor: NewUnsigned8},
		54:  {Name: "fragmentIdentification", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		55:  {Name: "postIpClassOfService", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		56:  {Name: "sourceMacAddress", Constructor: NewMacAddress, Semantics: semantics.Default},
		57:  {Name: "postDestinationMacAddress", Constructor: NewMacAddress, Semantics: semantics.Default},
		58:  {Name: "vlanId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		59:  {Name: "postVlanId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		60:  {Name: "ipVersion", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		61:  {Name: "flowDirection", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		62:  {Name: "ipNextHopIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		63:  {Name: "bgpNextHopIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		64:  {Name: "ipv6ExtensionHeaders", Constructor: NewUnsigned32, Semantics: semantics.Flags},
		65:  {Name: "Assigned for NetFlow v9 compatibility", Status: status.Undefined},
		66:  {Name: "Assigned for NetFlow v9 compatibility", Status: status.Undefined},
		67:  {Name: "Assigned for NetFlow v9 compatibility", Status: status.Undefined},
		68:  {Name: "Assigned for NetFlow v9 compatibility", Status: status.Undefined},
		69:  {Name: "Assigned for NetFlow v9 compatibility", Status: status.Undefined},
		70:  {Name: "mplsTopLabelStackSection", Constructor: NewOctetArray, Semantics: semantics.Default},
		71:  {Name: "mplsLabelStackSection2", Constructor: NewOctetArray, Semantics: semantics.Default},
		72:  {Name: "mplsLabelStackSection3", Constructor: NewOctetArray, Semantics: semantics.Default},
		73:  {Name: "mplsLabelStackSection4", Constructor: NewOctetArray, Semantics: semantics.Default},
		74:  {Name: "mplsLabelStackSection5", Constructor: NewOctetArray, Semantics: semantics.Default},
		75:  {Name: "mplsLabelStackSection6", Constructor: NewOctetArray, Semantics: semantics.Default},
		76:  {Name: "mplsLabelStackSection7", Constructor: NewOctetArray, Semantics: semantics.Default},
		77:  {Name: "mplsLabelStackSection8", Constructor: NewOctetArray, Semantics: semantics.Default},
		78:  {Name: "mplsLabelStackSection9", Constructor: NewOctetArray, Semantics: semantics.Default},
		79:  {Name: "mplsLabelStackSection10", Constructor: NewOctetArray, Semantics: semantics.Default},
		80:  {Name: "destinationMacAddress", Constructor: NewMacAddress, Semantics: semantics.Default},
		81:  {Name: "postSourceMacAddress", Constructor: NewMacAddress, Semantics: semantics.Default},
		82:  {Name: "interfaceName", Constructor: NewString, Semantics: semantics.Default},
		83:  {Name: "interfaceDescription", Constructor: NewString, Semantics: semantics.Default},
		84:  {Name: "samplerName", Constructor: NewString, Status: status.Deprecated},
		85:  {Name: "octetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		86:  {Name: "packetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		87:  {Name: "flagsAndSamplerId", Constructor: NewUnsigned32, Semantics: semantics.Identifier, Status: status.Deprecated},
		88:  {Name: "fragmentOffset", Constructor: NewUnsigned16, Semantics: semantics.Quantity},
		89:  {Name: "forwardingStatus", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		90:  {Name: "mplsVpnRouteDistinguisher", Constructor: NewOctetArray, Semantics: semantics.Default},
		91:  {Name: "mplsTopLabelPrefixLength", Constructor: NewUnsigned8, Semantics: semantics.Quantity},
		92:  {Name: "srcTrafficIndex", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		93:  {Name: "dstTrafficIndex", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		94:  {Name: "applicationDescription", Constructor: NewString, Semantics: semantics.Default},
		95:  {Name: "applicationId", Constructor: NewOctetArray, Semantics: semantics.Default},
		96:  {Name: "applicationName", Constructor: NewString, Semantics: semantics.Default},
		97:  {Name: "Assigned for NetFlow v9 compatibility", Status: status.Undefined},
		98:  {Name: "postIpDiffServCodePoint", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		99:  {Name: "multicastReplicationFactor", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		100: {Name: "className", Constructor: NewString, Status: status.Deprecated},
		101: {Name: "classificationEngineId", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		102: {Name: "layer2packetSectionOffset", Constructor: NewUnsigned16, Semantics: semantics.Quantity, Status: status.Deprecated},
		103: {Name: "layer2packetSectionSize", Constructor: NewUnsigned16, Semantics: semantics.Quantity, Status: status.Deprecated},
		104: {Name: "layer2packetSectionData", Constructor: NewOctetArray, Status: status.Deprecated},
		// 105-127 assigned for NFv9 compatibility
		128: {Name: "bgpNextAdjacentAsNumber", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		129: {Name: "bgpPrevAdjacentAsNumber", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		130: {Name: "exporterIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		131: {Name: "exporterIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		132: {Name: "droppedOctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		133: {Name: "droppedPacketDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		134: {Name: "droppedOctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		135: {Name: "droppedPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		136: {Name: "flowEndReason", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		137: {Name: "commonPropertiesId", Constructor: NewUnsigned64, Semantics: semantics.Identifier},
		138: {Name: "observationPointId", Constructor: NewUnsigned64, Semantics: semantics.Identifier},
		139: {Name: "icmpTypeCodeIPv6", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		140: {Name: "mplsTopLabelIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		141: {Name: "lineCardId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		142: {Name: "portId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		143: {Name: "meteringProcessId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		144: {Name: "exportingProcessId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		145: {Name: "templateId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		146: {Name: "wlanChannelId", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		147: {Name: "wlanSSID", Constructor: NewString, Semantics: semantics.Default},
		148: {Name: "flowId", Constructor: NewUnsigned64, Semantics: semantics.Identifier},
		149: {Name: "observationDomainId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		150: {Name: "flowStartSeconds", Constructor: NewDateTimeSeconds, Semantics: semantics.Default},
		151: {Name: "flowEndSeconds", Constructor: NewDateTimeSeconds, Semantics: semantics.Default},
		152: {Name: "flowStartMilliseconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		153: {Name: "flowEndMilliseconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		154: {Name: "flowStartMicroseconds", Constructor: NewDateTimeMicroseconds, Semantics: semantics.Default},
		155: {Name: "flowEndMicroseconds", Constructor: NewDateTimeMicroseconds, Semantics: semantics.Default},
		156: {Name: "flowStartNanoseconds", Constructor: NewDateTimeNanoseconds, Semantics: semantics.Default},
		157: {Name: "flowEndNanoseconds", Constructor: NewDateTimeNanoseconds, Semantics: semantics.Default},
		158: {Name: "flowStartDeltaMicroseconds", Constructor: NewUnsigned32},
		159: {Name: "flowEndDeltaMicroseconds", Constructor: NewUnsigned32},
		160: {Name: "systemInitTimeMilliseconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		161: {Name: "flowDurationMilliseconds", Constructor: NewUnsigned32},
		162: {Name: "flowDurationMicroseconds", Constructor: NewUnsigned32},
		163: {Name: "observedFlowTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		164: {Name: "ignoredPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		165: {Name: "ignoredOctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		166: {Name: "notSentFlowTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		167: {Name: "notSentPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		168: {Name: "notSentOctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		169: {Name: "destinationIPv6Prefix", Constructor: NewIPv6Address, Semantics: semantics.Default},
		170: {Name: "sourceIPv6Prefix", Constructor: NewIPv6Address, Semantics: semantics.Default},
		171: {Name: "postOctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		172: {Name: "postPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		173: {Name: "flowKeyIndicator", Constructor: NewUnsigned64, Semantics: semantics.Flags},
		174: {Name: "postMCastPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		175: {Name: "postMCastOctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		176: {Name: "icmpTypeIPv4", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		177: {Name: "icmpCodeIPv4", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		178: {Name: "icmpTypeIPv6", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		179: {Name: "icmpCodeIPv6", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		180: {Name: "udpSourcePort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		181: {Name: "udpDestinationPort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		182: {Name: "tcpSourcePort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		183: {Name: "tcpDestinationPort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		184: {Name: "tcpSequenceNumber", Constructor: NewUnsigned32},
		185: {Name: "tcpAcknowledgementNumber", Constructor: NewUnsigned32},
		186: {Name: "tcpWindowSize", Constructor: NewUnsigned16},
		187: {Name: "tcpUrgentPointer", Constructor: NewUnsigned16},
		188: {Name: "tcpHeaderLength", Constructor: NewUnsigned8},
		189: {Name: "ipHeaderLength", Constructor: NewUnsigned8},
		190: {Name: "totalLengthIPv4", Constructor: NewUnsigned16},
		191: {Name: "payloadLengthIPv6", Constructor: NewUnsigned16},
		192: {Name: "ipTTL", Constructor: NewUnsigned8},
		193: {Name: "nextHeaderIPv6", Constructor: NewUnsigned8},
		194: {Name: "mplsPayloadLength", Constructor: NewUnsigned32},
		195: {Name: "ipDiffServCodePoint", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		196: {Name: "ipPrecedence", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		197: {Name: "fragmentFlags", Constructor: NewUnsigned8, Semantics: semantics.Flags},
		198: {Name: "octetDeltaSumOfSquares", Constructor: NewUnsigned64},
		199: {Name: "octetTotalSumOfSquares", Constructor: NewUnsigned64},
		200: {Name: "mplsTopLabelTTL", Constructor: NewUnsigned8},
		201: {Name: "mplsLabelStackLength", Constructor: NewUnsigned32},
		202: {Name: "mplsLabelStackDepth", Constructor: NewUnsigned32},
		203: {Name: "mplsTopLabelExp", Constructor: NewUnsigned8, Semantics: semantics.Flags},
		204: {Name: "ipPayloadLength", Constructor: NewUnsigned32},
		205: {Name: "udpMessageLength", Constructor: NewUnsigned16},
		206: {Name: "isMulticast", Constructor: NewUnsigned8, Semantics: semantics.Flags},
		207: {Name: "ipv4IHL", Constructor: NewUnsigned8},
		208: {Name: "ipv4Options", Constructor: NewUnsigned32, Semantics: semantics.Flags},
		209: {Name: "tcpOptions", Constructor: NewUnsigned64, Semantics: semantics.Flags},
		210: {Name: "paddingOctets", Constructor: NewOctetArray, Semantics: semantics.Default},
		211: {Name: "collectorIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		212: {Name: "collectorIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		213: {Name: "exportInterface", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		214: {Name: "exportProtocolVersion", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		215: {Name: "exportTransportProtocol", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		216: {Name: "collectorTransportPort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		217: {Name: "exporterTransportPort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		218: {Name: "tcpSynTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		219: {Name: "tcpFinTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		220: {Name: "tcpRstTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		221: {Name: "tcpPshTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		222: {Name: "tcpAckTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		223: {Name: "tcpUrgTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		224: {Name: "ipTotalLength", Constructor: NewUnsigned64},
		225: {Name: "postNATSourceIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		226: {Name: "postNATDestinationIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		227: {Name: "postNAPTSourceTransportPort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		228: {Name: "postNAPTDestinationTransportPort", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		229: {Name: "natOriginatingAddressRealm", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		230: {Name: "natEvent", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		231: {Name: "initiatorOctets", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		232: {Name: "responderOctets", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		233: {Name: "firewallEvent", Constructor: NewUnsigned8},
		234: {Name: "ingressVRFID", Constructor: NewUnsigned32},
		235: {Name: "egressVRFID", Constructor: NewUnsigned32},
		236: {Name: "VRFname", Constructor: NewString, Semantics: semantics.Default},
		237: {Name: "postMplsTopLabelExp", Constructor: NewUnsigned8, Semantics: semantics.Flags},
		238: {Name: "tcpWindowScale", Constructor: NewUnsigned16},
		239: {Name: "biflowDirection", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		240: {Name: "ethernetHeaderLength", Constructor: NewUnsigned8, Semantics: semantics.Quantity},
		241: {Name: "ethernetPayloadLength", Constructor: NewUnsigned16, Semantics: semantics.Quantity},
		242: {Name: "ethernetTotalLength", Constructor: NewUnsigned16, Semantics: semantics.Quantity},
		243: {Name: "dot1qVlanId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		244: {Name: "dot1qPriority", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		245: {Name: "dot1qCustomerVlanId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		246: {Name: "dot1qCustomerPriority", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		247: {Name: "metroEvcId", Constructor: NewString, Semantics: semantics.Default},
		248: {Name: "metroEvcType", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		249: {Name: "pseudoWireId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		250: {Name: "pseudoWireType", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		251: {Name: "pseudoWireControlWord", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		252: {Name: "ingressPhysicalInterface", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		253: {Name: "egressPhysicalInterface", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		254: {Name: "postDot1qVlanId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		255: {Name: "postDot1qCustomerVlanId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		256: {Name: "ethernetType", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		257: {Name: "postIpPrecedence", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		258: {Name: "collectionTimeMilliseconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		259: {Name: "exportSctpStreamId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		260: {Name: "maxExportSeconds", Constructor: NewDateTimeSeconds, Semantics: semantics.Default},
		261: {Name: "maxFlowEndSeconds", Constructor: NewDateTimeSeconds, Semantics: semantics.Default},
		262: {Name: "messageMD5Checksum", Constructor: NewOctetArray, Semantics: semantics.Default},
		263: {Name: "messageScope", Constructor: NewUnsigned8},
		264: {Name: "minExportSeconds", Constructor: NewDateTimeSeconds, Semantics: semantics.Default},
		265: {Name: "minFlowStartSeconds", Constructor: NewDateTimeSeconds, Semantics: semantics.Default},
		266: {Name: "opaqueOctets", Constructor: NewOctetArray, Semantics: semantics.Default},
		267: {Name: "sessionScope", Constructor: NewUnsigned8},
		268: {Name: "maxFlowEndMicroseconds", Constructor: NewDateTimeMicroseconds, Semantics: semantics.Default},
		269: {Name: "maxFlowEndMilliseconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		270: {Name: "maxFlowEndNanoseconds", Constructor: NewDateTimeNanoseconds, Semantics: semantics.Default},
		271: {Name: "minFlowStartMicroseconds", Constructor: NewDateTimeMicroseconds, Semantics: semantics.Default},
		272: {Name: "minFlowStartMilliseconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		273: {Name: "minFlowStartNanoseconds", Constructor: NewDateTimeNanoseconds, Semantics: semantics.Default},
		274: {Name: "collectorCertificate", Constructor: NewOctetArray, Semantics: semantics.Default},
		275: {Name: "exporterCertificate", Constructor: NewOctetArray, Semantics: semantics.Default},
		276: {Name: "dataRecordsReliability", Constructor: NewBoolean, Semantics: semantics.Default},
		277: {Name: "observationPointType", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		278: {Name: "NewConnectionDeltaCount", Constructor: NewUnsigned32, Semantics: semantics.DeltaCounter},
		279: {Name: "connectionSumDurationSeconds", Constructor: NewUnsigned64},
		280: {Name: "connectionTransactionId", Constructor: NewUnsigned64, Semantics: semantics.Identifier},
		281: {Name: "postNATSourceIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		282: {Name: "postNATDestinationIPv6Address", Constructor: NewIPv6Address, Semantics: semantics.Default},
		283: {Name: "natPoolId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		284: {Name: "natPoolName", Constructor: NewString, Semantics: semantics.Default},
		285: {Name: "anonymizationFlags", Constructor: NewUnsigned16, Semantics: semantics.Flags},
		286: {Name: "anonymizationTechnique", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		287: {Name: "informationElementIndex", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		288: {Name: "p2pTechnology", Constructor: NewString, Semantics: semantics.Default},
		289: {Name: "tunnelTechnology", Constructor: NewString, Semantics: semantics.Default},
		290: {Name: "encryptedTechnology", Constructor: NewString, Semantics: semantics.Default},
		291: {Name: "basicList", Constructor: NewBasicList, Semantics: semantics.List},
		292: {Name: "subTemplateList", Constructor: NewDefaultSubTemplateList, Semantics: semantics.List},
		293: {Name: "subTemplateMultiList", Constructor: NewDefaultSubTemplateMultiList, Semantics: semantics.List},
		294: {Name: "bgpValidityState", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		295: {Name: "IPSecSPI", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		296: {Name: "greKey", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		297: {Name: "natType", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		298: {Name: "initiatorPackets", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		299: {Name: "responderPackets", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		300: {Name: "observationDomainName", Constructor: NewString, Semantics: semantics.Default},
		301: {Name: "selectionSequenceId", Constructor: NewUnsigned64, Semantics: semantics.Identifier},
		302: {Name: "selectorId", Constructor: NewUnsigned64, Semantics: semantics.Identifier},
		303: {Name: "informationElementId", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		304: {Name: "selectorAlgorithm", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		305: {Name: "samplingPacketInterval", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		306: {Name: "samplingPacketSpace", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		307: {Name: "samplingTimeInterval", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		308: {Name: "samplingTimeSpace", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		309: {Name: "samplingSize", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		310: {Name: "samplingPopulation", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		311: {Name: "samplingProbability", Constructor: NewFloat64, Semantics: semantics.Quantity},
		312: {Name: "dataLinkFrameSize", Constructor: NewUnsigned16, Semantics: semantics.Quantity},
		313: {Name: "ipHeaderPacketSection", Constructor: NewOctetArray, Semantics: semantics.Default},
		314: {Name: "ipPayloadPacketSection", Constructor: NewOctetArray, Semantics: semantics.Default},
		315: {Name: "dataLinkFrameSection", Constructor: NewOctetArray, Semantics: semantics.Default},
		316: {Name: "mplsLabelStackSection", Constructor: NewOctetArray, Semantics: semantics.Default},
		317: {Name: "mplsPayloadPacketSection", Constructor: NewOctetArray, Semantics: semantics.Default},
		318: {Name: "selectorIdTotalPktsObserved", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		319: {Name: "selectorIdTotalPktsSelected", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		320: {Name: "absoluteError", Constructor: NewFloat64, Semantics: semantics.Quantity},
		321: {Name: "relativeError", Constructor: NewFloat64, Semantics: semantics.Quantity},
		322: {Name: "observationTimeSeconds", Constructor: NewDateTimeSeconds, Semantics: semantics.Default},
		323: {Name: "observationTimeMilliseconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		324: {Name: "observationTimeMicroseconds", Constructor: NewDateTimeMicroseconds, Semantics: semantics.Default},
		325: {Name: "observationTimeNanoseconds", Constructor: NewDateTimeNanoseconds, Semantics: semantics.Default},
		326: {Name: "digestHashValue", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		327: {Name: "hashIPPayloadOffset", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		328: {Name: "hashIPPayloadSize", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		329: {Name: "hashOutputRangeMin", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		330: {Name: "hashOutputRangeMax", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		331: {Name: "hashSelectedRangeMin", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		332: {Name: "hashSelectedRangeMax", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		333: {Name: "hashDigestOutput", Constructor: NewBoolean, Semantics: semantics.Default},
		334: {Name: "hashInitialiserValue", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		335: {Name: "selectorName", Constructor: NewString, Semantics: semantics.Default},
		336: {Name: "upperCILimit", Constructor: NewFloat64, Semantics: semantics.Quantity},
		337: {Name: "lowerCILimit", Constructor: NewFloat64, Semantics: semantics.Quantity},
		338: {Name: "confidenceLevel", Constructor: NewFloat64, Semantics: semantics.Quantity},
		339: {Name: "informationElementDataType", Constructor: NewUnsigned8},
		340: {Name: "informationElementDescription", Constructor: NewString, Semantics: semantics.Default},
		341: {Name: "informationElementName", Constructor: NewString, Semantics: semantics.Default},
		342: {Name: "informationElementRangeBegin", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		343: {Name: "informationElementRangeEnd", Constructor: NewUnsigned64, Semantics: semantics.Quantity},
		344: {Name: "informationElementSemantics", Constructor: NewUnsigned8},
		345: {Name: "informationElementUnits", Constructor: NewUnsigned16},
		346: {Name: "privateEnterpriseNumber", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		347: {Name: "virtualStationInterfaceId", Constructor: NewOctetArray, Semantics: semantics.Default},
		348: {Name: "virtualStationInterfaceName", Constructor: NewString, Semantics: semantics.Default},
		349: {Name: "virtualStationUUID", Constructor: NewOctetArray, Semantics: semantics.Default},
		350: {Name: "virtualStationName", Constructor: NewString, Semantics: semantics.Default},
		351: {Name: "layer2SegmentId", Constructor: NewUnsigned64, Semantics: semantics.Identifier},
		352: {Name: "layer2OctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		353: {Name: "layer2OctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		354: {Name: "ingressUnicastPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		355: {Name: "ingressMulticastPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		356: {Name: "ingressBroadcastPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		357: {Name: "egressUnicastPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		358: {Name: "egressBroadcastPacketTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		359: {Name: "monitoringIntervalStartMilliSeconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		360: {Name: "monitoringIntervalEndMilliSeconds", Constructor: NewDateTimeMilliseconds, Semantics: semantics.Default},
		361: {Name: "portRangeStart", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		362: {Name: "portRangeEnd", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		363: {Name: "portRangeStepSize", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		364: {Name: "portRangeNumPorts", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		365: {Name: "staMacAddress", Constructor: NewMacAddress, Semantics: semantics.Default},
		366: {Name: "staIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		367: {Name: "wtpMacAddress", Constructor: NewMacAddress, Semantics: semantics.Default},
		368: {Name: "ingressInterfaceType", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		369: {Name: "egressInterfaceType", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		370: {Name: "rtpSequenceNumber", Constructor: NewUnsigned16},
		371: {Name: "userName", Constructor: NewString, Semantics: semantics.Default},
		372: {Name: "applicationCategoryName", Constructor: NewString, Semantics: semantics.Default},
		373: {Name: "applicationSubCategoryName", Constructor: NewString, Semantics: semantics.Default},
		374: {Name: "applicationGroupName", Constructor: NewString, Semantics: semantics.Default},
		375: {Name: "originalFlowsPresent", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		376: {Name: "originalFlowsInitiated", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		377: {Name: "originalFlowsCompleted", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		378: {Name: "distinctCountOfSourceIPAddress", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		379: {Name: "distinctCountOfDestinationIPAddress", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		380: {Name: "distinctCountOfSourceIPv4Address", Constructor: NewUnsigned32, Semantics: semantics.TotalCounter},
		381: {Name: "distinctCountOfDestinationIPv4Address", Constructor: NewUnsigned32, Semantics: semantics.TotalCounter},
		382: {Name: "distinctCountOfSourceIPv6Address", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		383: {Name: "distinctCountOfDestinationIPv6Address", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		384: {Name: "valueDistributionMethod", Constructor: NewUnsigned8},
		385: {Name: "rfc3550JitterMilliseconds", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		386: {Name: "rfc3550JitterMicroseconds", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		387: {Name: "rfc3550JitterNanoseconds", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		388: {Name: "dot1qDEI", Constructor: NewBoolean, Semantics: semantics.Default},
		389: {Name: "dot1qCustomerDEI", Constructor: NewBoolean, Semantics: semantics.Default},
		390: {Name: "flowSelectorAlgorithm", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		391: {Name: "flowSelectedOctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		392: {Name: "flowSelectedPacketDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		393: {Name: "flowSelectedFlowDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		394: {Name: "selectorIDTotalFlowsObserved", Constructor: NewUnsigned64},
		395: {Name: "selectorIDTotalFlowsSelected", Constructor: NewUnsigned64},
		396: {Name: "samplingFlowInterval", Constructor: NewUnsigned64},
		397: {Name: "samplingFlowSpacing", Constructor: NewUnsigned64},
		398: {Name: "flowSamplingTimeInterval", Constructor: NewUnsigned64},
		399: {Name: "flowSamplingTimeSpacing", Constructor: NewUnsigned64},
		400: {Name: "hashFlowDomain", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		401: {Name: "transportOctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		402: {Name: "transportPacketDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		403: {Name: "originalExporterIPv4Address", Constructor: NewIPv4Address},
		404: {Name: "originalExporterIPv6Address", Constructor: NewIPv6Address},
		405: {Name: "originalObservationDomainId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		406: {Name: "intermediateProcessId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		407: {Name: "ignoredDataRecordTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		408: {Name: "dataLinkFrameType", Constructor: NewUnsigned16, Semantics: semantics.Flags},
		409: {Name: "sectionOffset", Constructor: NewUnsigned16, Semantics: semantics.Quantity},
		410: {Name: "sectionExportedOctets", Constructor: NewUnsigned16, Semantics: semantics.Quantity},
		411: {Name: "dot1qServiceInstanceTag", Constructor: NewOctetArray, Semantics: semantics.Default},
		412: {Name: "dot1qServiceInstanceId", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		413: {Name: "dot1qServiceInstancePriority", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		414: {Name: "dot1qCustomerSourceMacAddress", Constructor: NewMacAddress, Semantics: semantics.Default},
		415: {Name: "dot1qCustomerDestinationMacAddress", Constructor: NewMacAddress, Semantics: semantics.Default},
		416: {Name: "", Status: status.Deprecated},
		417: {Name: "postLayer2OctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		418: {Name: "postMCastLayer2OctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		419: {Name: "", Status: status.Deprecated},
		420: {Name: "postLayer2OctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		421: {Name: "postMCastLayer2OctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		422: {Name: "minimumLayer2TotalLength", Constructor: NewUnsigned64},
		423: {Name: "maximumLayer2TotalLength", Constructor: NewUnsigned64},
		424: {Name: "droppedLayer2OctetDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		425: {Name: "droppedLayer2OctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		426: {Name: "ignoredLayer2OctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		427: {Name: "notSentLayer2OctetTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		428: {Name: "layer2OctetDeltaSumOfSquares", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		429: {Name: "layer2OctetTotalSumOfSquares", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		430: {Name: "layer2FrameDeltaCount", Constructor: NewUnsigned64, Semantics: semantics.DeltaCounter},
		431: {Name: "layer2FrameTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		432: {Name: "pseudoWireDestinationIPv4Address", Constructor: NewIPv4Address, Semantics: semantics.Default},
		433: {Name: "ignoredLayer2FrameTotalCount", Constructor: NewUnsigned64, Semantics: semantics.TotalCounter},
		434: {Name: "mibObjectValueInteger", Constructor: NewSigned32, Semantics: semantics.Quantity},
		435: {Name: "mibObjectValueOctetString", Constructor: NewOctetArray, Semantics: semantics.Default},
		436: {Name: "mibObjectValueOID", Constructor: NewOctetArray, Semantics: semantics.Default},
		437: {Name: "mibObjectValueBits", Constructor: NewOctetArray, Semantics: semantics.Default},
		438: {Name: "mibObjectValueIPAddress", Constructor: NewIPv4Address, Semantics: semantics.Default},
		439: {Name: "mibObjectValueCounter", Constructor: NewUnsigned64, Semantics: semantics.SNMPCounter},
		440: {Name: "mibObjectValueGauge", Constructor: NewUnsigned32, Semantics: semantics.SNMPGauge},
		441: {Name: "mibObjectValueTimeTicks", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		442: {Name: "mibObjectValueUnsigned", Constructor: NewUnsigned32, Semantics: semantics.Quantity},
		443: {Name: "mibObjectValueTable", Constructor: NewDefaultSubTemplateList, Semantics: semantics.List},
		444: {Name: "mibObjectValueRow", Constructor: NewDefaultSubTemplateList, Semantics: semantics.List},
		445: {Name: "mibObjectIdentifier", Constructor: NewOctetArray, Semantics: semantics.Default},
		446: {Name: "mibSubIdentifier", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		447: {Name: "mibIndexIndicator", Constructor: NewUnsigned64, Semantics: semantics.Flags},
		448: {Name: "mibCaptureTimeSemantics", Constructor: NewUnsigned8, Semantics: semantics.Identifier},
		449: {Name: "mibContextEngineID", Constructor: NewOctetArray, Semantics: semantics.Default},
		450: {Name: "mibContextName", Constructor: NewString, Semantics: semantics.Default},
		451: {Name: "mibObjectName", Constructor: NewString, Semantics: semantics.Default},
		452: {Name: "mibObjectDescription", Constructor: NewString, Semantics: semantics.Default},
		453: {Name: "mibObjectSyntax", Constructor: NewString, Semantics: semantics.Default},
		454: {Name: "mibModuleName", Constructor: NewString, Semantics: semantics.Default},
		455: {Name: "mobileIMSI", Constructor: NewString, Semantics: semantics.Default},
		456: {Name: "mobileMSISDN", Constructor: NewString, Semantics: semantics.Default},
		457: {Name: "httpStatusCode", Constructor: NewUnsigned16, Semantics: semantics.Identifier},
		458: {Name: "sourceTransportPortsLimit", Constructor: NewUnsigned16, Semantics: semantics.Quantity},
		459: {Name: "httpRequestMethod", Constructor: NewString},
		460: {Name: "httpRequestHost", Constructor: NewString},
		461: {Name: "httpRequestTarget", Constructor: NewString},
		462: {Name: "httpMessageVersion", Constructor: NewString},
		463: {Name: "natInstanceID", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		464: {Name: "internalAddressRealm", Constructor: NewOctetArray, Semantics: semantics.Identifier},
		465: {Name: "externalAddressRealm", Constructor: NewOctetArray, Semantics: semantics.Identifier},
		466: {Name: "natQuotaExceededEvent", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		467: {Name: "natThresholdEvent", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		468: {Name: "httpUserAgent", Constructor: NewString, Semantics: semantics.Default},
		469: {Name: "httpContentType", Constructor: NewString, Semantics: semantics.Default},
		470: {Name: "httpReasonPhrase", Constructor: NewString, Semantics: semantics.Default},
		471: {Name: "maxSessionEntries", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		472: {Name: "maxBIBEntries", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		473: {Name: "maxEntriesPerUser", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		474: {Name: "maxSubscribers", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		475: {Name: "maxFragmentsPendingReassembly", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		476: {Name: "addressPoolHighThreshold", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		477: {Name: "addressPoolLowThreshold", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		478: {Name: "addressPortMappingHighThreshold", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		479: {Name: "addressPortMappingLowThreshold", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		480: {Name: "addressPortMappingPerUserHighThreshold", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		481: {Name: "globalAddressMappingHighThreshold", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		482: {Name: "vpnIdentifier", Constructor: NewOctetArray, Semantics: semantics.Default},
		483: {Name: "bgpCommunity", Constructor: NewUnsigned32, Semantics: semantics.Identifier},
		484: {Name: "bgpSourceCommunityList", Constructor: NewBasicList, Semantics: semantics.List},
		485: {Name: "bgpDestinationCommunityList", Constructor: NewBasicList, Semantics: semantics.List},
		486: {Name: "bgpExtendedCommunity", Constructor: NewOctetArray, Semantics: semantics.Default},
		487: {Name: "bgpSourceExtendedCommunityList", Constructor: NewBasicList, Semantics: semantics.List},
		488: {Name: "bgpDestinationExtendedCommunityList", Constructor: NewBasicList, Semantics: semantics.List},
		489: {Name: "bgpLargeCommunity", Constructor: NewOctetArray, Semantics: semantics.Default},
		490: {Name: "bgpSourceLargeCommunityList", Constructor: NewBasicList, Semantics: semantics.List},
		491: {Name: "bgpDestinationLargeCommunityList", Constructor: NewBasicList, Semantics: semantics.List},
	}*/
}

func IPFIX() map[uint16]InformationElement {
	return ianaIpfixIEs
}

func CERT() map[uint16]InformationElement {
	return certIpfixIEs
}
